### ISSUE TITLE
Document OctoFarm export and import into FDM Monster

### ISSUE THREAD

**Issue by davidzwa** [fdm-monster/fdm-monster-docs#125]
The OctoFarm export procedure has been recently tested, but it lacks in the documentation.

## Task Description
- [ ] Provide the GIF or a better version of it
- [ ] Document the place to upload the "PrintersDB.json" file
- [ ] Document what is imported, and what is not

![octofarm-printer-export](https://github.com/fdm-monster/fdm-monster-docs/assets/6005355/cf5974b0-c6e5-41b7-b281-cdb0b21a0be8)
