### ISSUE TITLE
Document upgrade path from MonsterPi 0.3 to 0.4

### ISSUE THREAD

**Issue by davidzwa** [fdm-monster/fdm-monster-docs#132]
Users need to be given a path forward from the old MonsterPi to the new one. I personally have the intuition that YAML export is a reliable method.

## Task description
- [ ] Explain that the steps are to export YAML, flash a new SD card (so the known steps) and import the YAML
- [ ] Explain that users should always verify and correct the exported YAML file for errors. Recommend them to look for missing properties like printer `name` value. Also provide them a disclaimer that only printers and floors are exported with this method (so no user accounts)
- [ ] Explain to them that other options are available with mongodump and mongorestore, but it is outside the scope of this documentation as it is quite advanced
